const fs = require('fs');
const path = require('path');

// Generate a report
const generateReport = async (reportType, generatedBy) => {
  try {
    const timestamp = new Date().toISOString();
    const reportContent = `Report Type: ${reportType}\nGenerated By: ${generatedBy}\nTimestamp: ${timestamp}`;
    const reportPath = path.join(__dirname, `../reports/${reportType}-${Date.now()}.txt`);

    // Save the report to a file
    fs.writeFileSync(reportPath, reportContent);

    return { reportPath, reportContent };
  } catch (error) {
    console.error('Error generating report:', error);
    throw error;
  }
};

module.exports = { generateReport };